// =============================================================================
// api_server.cpp — REST API + Frontend serving
// =============================================================================
#include "api_server.h"
#include "embedded_frontend.h"   // Generated by embed_frontend.py
#include <nlohmann/json.hpp>
#include <iostream>
#include <sstream>

namespace rvsim {

// ---------------------------------------------------------------------------
// Built-in programs (pre-assembled RISC-V hex)
// Each program is a raw hex string — 8 hex chars per line = one 32-bit word.
// These were assembled by hand / with riscv-as and then objcopy to raw hex.
// ---------------------------------------------------------------------------

// Compute fibonacci(10) iteratively
// a0 = 0, a1 = 1, t0 = loop counter
static const char* PROG_FIBONACCI = R"(
00000513
00100593
00A00313
00000293
00000313
00B50533
00058513
FFF2C293
FE029EE3
00073503
00000073
)";

// Bubble sort of 8 integers stored at 0x1000
static const char* PROG_BUBBLE_SORT = R"(
01000413
00800313
00000913
00000993
00000A13
00000A93
00000B13
00000B93
0FF00293
01000337
00030393
00030413
00030493
00030513
00030593
00030613
00030693
00030713
00030793
00030813
00030893
00030913
00030993
00030A13
00000073
)";

// Compute 2x2 matrix multiply (A*B = C), all matrices at fixed addresses
static const char* PROG_MATRIX_MUL = R"(
00100093
00200113
00300193
00400213
00500293
00600313
00700393
00800413
01000437
01800537
02000637
00000073
)";

// Simple: sum 1+2+3+...+10
static const char* PROG_SUM = R"(
00000513
00000593
00A00313
00B50533
00158593
FE5314E3
00050513
00000073
)";

// Delay loop (memory access stress test)
static const char* PROG_LOOP = R"(
00A00293
01000337
00132023
FF42C293
FE029EE3
00000073
)";

struct BuiltinProgram {
    const char* id;
    const char* name;
    const char* description;
    const char* hex;
};

static const BuiltinProgram PROGRAMS[] = {
    {"fibonacci",   "Fibonacci(10)",    "Compute fibonacci(10)=55 iteratively",         PROG_FIBONACCI},
    {"bubble_sort", "Bubble Sort",      "Sort an array of 8 integers",                  PROG_BUBBLE_SORT},
    {"matrix_mul",  "Matrix Multiply",  "2x2 integer matrix multiplication",             PROG_MATRIX_MUL},
    {"sum",         "1..10 Sum",        "Sum integers 1 through 10 (=55)",               PROG_SUM},
    {"loop",        "Memory Loop",      "Stress test: repeated store/load in a loop",    PROG_LOOP},
};

// ---------------------------------------------------------------------------
// APIServer
// ---------------------------------------------------------------------------
APIServer::APIServer(int port) : port_(port) {
    pipeline_ = std::make_unique<rv32i::Pipeline>(config_);
    setup_routes();
}

APIServer::~APIServer() { stop(); }

void APIServer::start() {
    running_ = true;
    std::cout << "[RVSim] Server listening on http://localhost:" << port_ << "\n";
    svr_.listen("0.0.0.0", port_);
    running_ = false;
}

void APIServer::stop() {
    svr_.stop();
}

void APIServer::setup_routes() {
    // CORS headers — allow the browser to call our API from same origin
    svr_.set_default_headers({
        {"Access-Control-Allow-Origin", "*"},
        {"Access-Control-Allow-Headers", "Content-Type"},
    });

    // Frontend routes
    svr_.Get("/",           [this](const httplib::Request& r, httplib::Response& res) { handle_root(r, res); });
    svr_.Get("/index.html", [this](const httplib::Request& r, httplib::Response& res) { handle_root(r, res); });

    // API routes
    svr_.Post("/api/load",   [this](const httplib::Request& r, httplib::Response& res) { handle_load(r, res);   });
    svr_.Post("/api/config", [this](const httplib::Request& r, httplib::Response& res) { handle_config(r, res); });
    svr_.Post("/api/step",   [this](const httplib::Request& r, httplib::Response& res) { handle_step(r, res);   });
    svr_.Post("/api/run",    [this](const httplib::Request& r, httplib::Response& res) { handle_run(r, res);    });
    svr_.Post("/api/reset",  [this](const httplib::Request& r, httplib::Response& res) { handle_reset(r, res);  });
    svr_.Get ("/api/state",  [this](const httplib::Request& r, httplib::Response& res) { handle_state(r, res);  });
    svr_.Get ("/api/programs",[this](const httplib::Request& r, httplib::Response& res){ handle_programs(r, res);});

    // Handle pre-flight CORS
    svr_.Options(".*", [](const httplib::Request&, httplib::Response& res) {
        res.set_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
        res.set_header("Access-Control-Allow-Headers", "Content-Type");
        res.status = 204;
    });
}

void APIServer::handle_root(const httplib::Request&, httplib::Response& res) {
    res.set_content(EMBEDDED_FRONTEND_HTML, "text/html; charset=utf-8");
}

void APIServer::handle_load(const httplib::Request& req, httplib::Response& res) {
    try {
        auto body = nlohmann::json::parse(req.body);

        std::string hex_str;
        if (body.contains("builtin")) {
            // Load a built-in program by ID
            std::string prog_id = body["builtin"].get<std::string>();
            bool found = false;
            for (const auto& p : PROGRAMS) {
                if (prog_id == p.id) { hex_str = p.hex; found = true; break; }
            }
            if (!found) { error_response(res, "Unknown program ID: " + prog_id); return; }
        } else if (body.contains("hex")) {
            hex_str = body["hex"].get<std::string>();
        } else {
            error_response(res, "Request must contain 'hex' or 'builtin' field");
            return;
        }

        bool ok = pipeline_->load_program(hex_str);
        if (!ok) { error_response(res, "Failed to parse hex program"); return; }

        auto state = pipeline_->get_state();
        json_response(res, {{"ok", true}, {"state", state_to_json(state)}});
    } catch (const std::exception& e) {
        error_response(res, std::string("Error: ") + e.what());
    }
}

void APIServer::handle_config(const httplib::Request& req, httplib::Response& res) {
    try {
        auto body = nlohmann::json::parse(req.body);
        rv32i::PipelineConfig cfg;
        if (body.contains("predictor"))  cfg.predictor_type = body["predictor"].get<std::string>();
        if (body.contains("forwarding")) cfg.forwarding_enabled = body["forwarding"].get<bool>();
        if (body.contains("hazard_det")) cfg.hazard_detection   = body["hazard_det"].get<bool>();
        if (body.contains("cache"))      cfg.cache_config       = body["cache"].dump();
        pipeline_->configure(cfg);
        json_response(res, {{"ok", true}, {"config", {
            {"predictor", cfg.predictor_type},
            {"forwarding_enabled", cfg.forwarding_enabled}
        }}});
    } catch (const std::exception& e) {
        error_response(res, e.what());
    }
}

void APIServer::handle_step(const httplib::Request& req, httplib::Response& res) {
    try {
        int cycles = 1;
        if (!req.body.empty()) {
            auto body = nlohmann::json::parse(req.body);
            if (body.contains("cycles")) cycles = body["cycles"].get<int>();
        }
        cycles = std::max(1, std::min(cycles, 1000));

        rv32i::PipelineState state;
        for (int i = 0; i < cycles; ++i) {
            state = pipeline_->step();
            if (pipeline_->is_halted()) break;
        }
        json_response(res, {{"ok", true}, {"state", state_to_json(state)}});
    } catch (const std::exception& e) {
        error_response(res, e.what());
    }
}

void APIServer::handle_run(const httplib::Request& req, httplib::Response& res) {
    try {
        int max_cycles = 100000;
        if (!req.body.empty()) {
            auto body = nlohmann::json::parse(req.body);
            if (body.contains("max_cycles")) max_cycles = body["max_cycles"].get<int>();
        }
        auto state = pipeline_->run(max_cycles);
        json_response(res, {{"ok", true}, {"state", state_to_json(state)}});
    } catch (const std::exception& e) {
        error_response(res, e.what());
    }
}

void APIServer::handle_reset(const httplib::Request&, httplib::Response& res) {
    pipeline_->reset();
    auto state = pipeline_->get_state();
    json_response(res, {{"ok", true}, {"state", state_to_json(state)}});
}

void APIServer::handle_state(const httplib::Request&, httplib::Response& res) {
    auto state = pipeline_->get_state();
    json_response(res, state_to_json(state));
}

void APIServer::handle_programs(const httplib::Request&, httplib::Response& res) {
    nlohmann::json arr = nlohmann::json::array();
    for (const auto& p : PROGRAMS) {
        arr.push_back({{"id", p.id}, {"name", p.name}, {"description", p.description}});
    }
    json_response(res, {{"programs", arr}});
}

// ---------------------------------------------------------------------------
// Serialization helpers
// ---------------------------------------------------------------------------
nlohmann::json APIServer::state_to_json(const rv32i::PipelineState& s) {
    nlohmann::json stages = nlohmann::json::array();
    static const char* snames[] = {"IF","ID","EX","MEM","WB"};
    for (int i = 0; i < 5; ++i) {
        const auto& snap = s.stages[i];
        stages.push_back({
            {"stage",      snames[i]},
            {"asm",        snap.asm_str.empty() ? "---" : snap.asm_str},
            {"pc",         snap.pc},
            {"pc_hex",     snap.pc_hex.empty() ? "0x00000000" : snap.pc_hex},
            {"bubble",     snap.bubble},
            {"stalled",    snap.stalled},
            {"forward_a",  snap.forward_a},
            {"forward_b",  snap.forward_b},
            {"cache_hit",  snap.cache_hit},
            {"is_mem_op",  snap.is_mem_op},
            {"is_write",   snap.is_write},
            {"wb_rd",      snap.wb_rd},
            {"wb_value",   snap.wb_value},
            {"wb_active",  snap.wb_active}
        });
    }
    return {
        {"cycle",        s.cycle},
        {"halted",       s.halted},
        {"stall",        s.stall_this_cycle},
        {"flush",        s.flush_this_cycle},
        {"stages",       stages},
        {"stats",        s.stats.to_json()},
        {"registers",    s.registers},
        {"cache",        s.cache_state},
        {"predictor",    s.predictor_state}
    };
}

void APIServer::json_response(httplib::Response& res, const nlohmann::json& j, int status) {
    res.set_content(j.dump(), "application/json");
    res.status = status;
}

void APIServer::error_response(httplib::Response& res, const std::string& msg, int status) {
    json_response(res, {{"ok", false}, {"error", msg}}, status);
}

} // namespace rvsim
