#!/usr/bin/env python3
"""
embed_frontend.py — Bakes frontend/index.html into a C++ header file.

Usage: python embed_frontend.py <input.html> <output_header.h>

The output header defines a single const char* variable:
    EMBEDDED_FRONTEND_HTML
which the C++ HTTP server includes and serves directly.
"""
import sys
import os

def embed(input_path: str, output_path: str):
    with open(input_path, 'r', encoding='utf-8') as f:
        html = f.read()

    # Escape backslashes and double-quotes for C++ string literal
    # We use a raw string literal (C++11) to avoid most escaping issues.
    # The only thing we need to handle is the sequence )"; which would end
    # the raw string early.
    DELIMITER = "RVSIM_EMBED"

    header = f"""// AUTO-GENERATED by tools/embed_frontend.py — DO NOT EDIT MANUALLY
// Source: {os.path.basename(input_path)}
// Generated: {__import__('datetime').datetime.now().isoformat()}
#pragma once

static const char* EMBEDDED_FRONTEND_HTML = R"{DELIMITER}(
{html}
){DELIMITER}";
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(header)

    size_kb = len(html) / 1024
    print(f"[embed_frontend] {os.path.basename(input_path)} → {os.path.basename(output_path)} ({size_kb:.1f} KB)")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: embed_frontend.py <input.html> <output.h>")
        sys.exit(1)
    embed(sys.argv[1], sys.argv[2])
