// =============================================================================
// rv32i_pkg.sv — RISC-V RV32I ISA Package
// =============================================================================
// SystemVerilog package containing all constants, types, and struct definitions
// for the RV32I base integer instruction set.
//
// This is the Verilog equivalent of rv32i_types.h from the C++ simulator.
// Every module in the processor imports this package.
// =============================================================================
`ifndef RV32I_PKG_SV
`define RV32I_PKG_SV

package rv32i_pkg;

  // =========================================================================
  // Opcodes (bits [6:0] of every instruction)
  // =========================================================================
  typedef enum logic [6:0] {
    OP_LOAD    = 7'b000_0011,   // LB, LH, LW, LBU, LHU
    OP_STORE   = 7'b010_0011,   // SB, SH, SW
    OP_BRANCH  = 7'b110_0011,   // BEQ, BNE, BLT, BGE, BLTU, BGEU
    OP_JALR    = 7'b110_0111,   // JALR
    OP_JAL     = 7'b110_1111,   // JAL
    OP_IMM     = 7'b001_0011,   // ADDI, SLTI, SLTIU, XORI, ORI, ANDI, SLLI, SRLI, SRAI
    OP_REG     = 7'b011_0011,   // ADD, SUB, SLL, SLT, SLTU, XOR, SRL, SRA, OR, AND
    OP_LUI     = 7'b011_0111,   // LUI
    OP_AUIPC   = 7'b001_0111,   // AUIPC
    OP_SYSTEM  = 7'b111_0011,   // ECALL, EBREAK
    OP_FENCE   = 7'b000_1111    // FENCE (treated as NOP)
  } opcode_t;

  // =========================================================================
  // ALU Operation Select
  // =========================================================================
  typedef enum logic [3:0] {
    ALU_ADD  = 4'b0000,
    ALU_SUB  = 4'b0001,
    ALU_SLL  = 4'b0010,
    ALU_SLT  = 4'b0011,
    ALU_SLTU = 4'b0100,
    ALU_XOR  = 4'b0101,
    ALU_SRL  = 4'b0110,
    ALU_SRA  = 4'b0111,
    ALU_OR   = 4'b1000,
    ALU_AND  = 4'b1001,
    ALU_PASS_B = 4'b1010   // Pass operand B through (for LUI)
  } alu_op_t;

  // =========================================================================
  // funct3 field constants — Branch
  // =========================================================================
  localparam logic [2:0] F3_BEQ  = 3'b000;
  localparam logic [2:0] F3_BNE  = 3'b001;
  localparam logic [2:0] F3_BLT  = 3'b100;
  localparam logic [2:0] F3_BGE  = 3'b101;
  localparam logic [2:0] F3_BLTU = 3'b110;
  localparam logic [2:0] F3_BGEU = 3'b111;

  // =========================================================================
  // funct3 field constants — Load/Store
  // =========================================================================
  localparam logic [2:0] F3_BYTE  = 3'b000;  // LB / SB
  localparam logic [2:0] F3_HALF  = 3'b001;  // LH / SH
  localparam logic [2:0] F3_WORD  = 3'b010;  // LW / SW
  localparam logic [2:0] F3_BYTEU = 3'b100;  // LBU
  localparam logic [2:0] F3_HALFU = 3'b101;  // LHU

  // =========================================================================
  // funct3 field constants — ALU immediate / register ops
  // =========================================================================
  localparam logic [2:0] F3_ADD_SUB = 3'b000;
  localparam logic [2:0] F3_SLL     = 3'b001;
  localparam logic [2:0] F3_SLT     = 3'b010;
  localparam logic [2:0] F3_SLTU    = 3'b011;
  localparam logic [2:0] F3_XOR     = 3'b100;
  localparam logic [2:0] F3_SRL_SRA = 3'b101;
  localparam logic [2:0] F3_OR      = 3'b110;
  localparam logic [2:0] F3_AND     = 3'b111;

  // =========================================================================
  // funct7 differentiators
  // =========================================================================
  localparam logic [6:0] F7_NORMAL = 7'b000_0000;  // ADD, SRL
  localparam logic [6:0] F7_ALT    = 7'b010_0000;  // SUB, SRA

  // =========================================================================
  // Forwarding MUX Select
  // =========================================================================
  typedef enum logic [1:0] {
    FWD_NONE   = 2'b00,   // No forwarding — use register file value
    FWD_EX_MEM = 2'b01,   // Forward from EX/MEM pipeline register
    FWD_MEM_WB = 2'b10    // Forward from MEM/WB pipeline register
  } forward_sel_t;

  // =========================================================================
  // Control Signals — generated by the control unit, travel through pipeline
  // =========================================================================
  typedef struct packed {
    logic       reg_write;    // Write result to register file (WB)
    logic       mem_read;     // Read from data memory (MEM)
    logic       mem_write;    // Write to data memory (MEM)
    logic       mem_to_reg;   // WB mux: 1=mem data, 0=ALU result
    logic       alu_src;      // EX mux: 1=immediate, 0=rs2
    logic       branch;       // Conditional branch instruction
    logic       jump;         // JAL
    logic       jalr;         // JALR
    logic       lui;          // LUI
    logic       auipc;        // AUIPC
    logic       is_ecall;     // System halt
    logic [2:0] funct3;       // Sub-opcode (for load/store size, branch type)
    logic [6:0] funct7;       // Sub-opcode (for ADD/SUB, SRL/SRA)
    alu_op_t    alu_op;       // ALU operation select
  } ctrl_signals_t;

  // =========================================================================
  // Pipeline Register Structures
  // =========================================================================

  // IF/ID Pipeline Register
  typedef struct packed {
    logic [31:0] instruction;  // Raw 32-bit instruction
    logic [31:0] pc;           // PC of this instruction
    logic [31:0] pc_plus4;     // PC + 4
    logic        valid;        // false = bubble/NOP
  } if_id_reg_t;

  // ID/EX Pipeline Register
  typedef struct packed {
    logic [31:0] pc;
    logic [31:0] pc_plus4;
    logic [31:0] rs1_data;     // Register file read data 1
    logic [31:0] rs2_data;     // Register file read data 2
    logic [31:0] imm;          // Sign-extended immediate
    logic [4:0]  rs1;          // Source register 1 index
    logic [4:0]  rs2;          // Source register 2 index
    logic [4:0]  rd;           // Destination register index
    ctrl_signals_t ctrl;       // Control signals
    logic        valid;
  } id_ex_reg_t;

  // EX/MEM Pipeline Register
  typedef struct packed {
    logic [31:0] pc;
    logic [31:0] pc_plus4;
    logic [31:0] alu_result;   // ALU output / memory address
    logic [31:0] rs2_data;     // Store data
    logic [4:0]  rd;
    logic        branch_taken; // Branch was taken
    logic [31:0] branch_target;// Branch/jump target PC
    ctrl_signals_t ctrl;
    logic        valid;
  } ex_mem_reg_t;

  // MEM/WB Pipeline Register
  typedef struct packed {
    logic [31:0] pc;
    logic [31:0] alu_result;
    logic [31:0] mem_data;     // Data read from memory
    logic [4:0]  rd;
    logic [31:0] pc_plus4;
    ctrl_signals_t ctrl;
    logic        valid;
  } mem_wb_reg_t;

  // =========================================================================
  // NOP instruction constant (ADDI x0, x0, 0)
  // =========================================================================
  localparam logic [31:0] NOP_INSTR = 32'h0000_0013;

  // =========================================================================
  // Helper functions
  // =========================================================================

  // Extract opcode from raw instruction
  function automatic opcode_t get_opcode(input logic [31:0] instr);
    return opcode_t'(instr[6:0]);
  endfunction

  // Extract register fields
  function automatic logic [4:0] get_rd(input logic [31:0] instr);
    return instr[11:7];
  endfunction

  function automatic logic [4:0] get_rs1(input logic [31:0] instr);
    return instr[19:15];
  endfunction

  function automatic logic [4:0] get_rs2(input logic [31:0] instr);
    return instr[24:20];
  endfunction

  function automatic logic [2:0] get_funct3(input logic [31:0] instr);
    return instr[14:12];
  endfunction

  function automatic logic [6:0] get_funct7(input logic [31:0] instr);
    return instr[31:25];
  endfunction

endpackage

`endif
